name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar o Poetry
        run:  pipx install poetry
      
      - name: Instalar as dependências
        run:  poetry install